# Generated by Django 5.1.5 on 2025-01-23 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salesdata',
            table='data_salesdata',
        ),
    ]
