# Generated by Django 5.1.5 on 2025-01-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='units_sold',
            field=models.IntegerField(),
        ),
    ]
